### ISSUE TITLE
Переделать структуру lang файла на json

### ISSUE THREAD

**Issue by greshniksv** [MegoHappyThreeFriends/JustTrade#12]
Переделать файл содержащий локализацию, с обычного текста. На json формат.

**Comment by greshniksv** [comment]
И записать тест на этот класс.

**Comment by greshniksv** [comment]
Сомневаюсь в необходимости

**Comment by greshniksv** [comment]
Необходимо обдумать варианты форматов локализаций.

**Comment by dimerr** [comment]
On 06/15/2015 05:03 PM, Сергей Раткин wrote:
>
> Необходимо обдумать варианты форматов локализаций.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MegoHappyThreeFriends/JustTrade/issues/12#issuecomment-112081107>.
>
а шо тут обдумывать, формат должен быть не самодельный, а какой-то из 
обще-популярных, джсон вполне нормально выглядит в данном случае

-- 
  Dmitry Ermakov

**Comment by greshniksv** [comment]
Дааа, с самое главное что json, можно будет передать яве в случае чего, чтобы отображать сообщения или еще какую нить информацию на необходимой локализации.

**Comment by greshniksv** [comment]
готово
