### ISSUE TITLE
Сортировака Lang файла

### ISSUE THREAD

**Issue by greshniksv** [MegoHappyThreeFriends/JustTrade#15]
Необходимо сделать механизм сортировки Lang файла.
Я думаю пока его нужно извлечь из ресурсов и положить в папку и при каждом запуске выполнять сортирувку его.
Сортировка необходимо для того чтобы не плодить дебликаты, там пока 20 строк но я уже пару раз задублировал параметры :confused:

**Comment by dimerr** [comment]
ну так может тогда и редактор нужен, который и будет на выходе 
сортировать файл. нужен ли этот функционал в основном коде?

On 06/10/2015 10:49 AM, Сергей Раткин wrote:
>
> Необходимо сделать механизм сортировки Lang файла.
> Я думаю пока его нужно извлечь из ресурсов и положить в папку и при 
> каждом запуске выполнять сортирувку его.
> Сортировка необходимо для того чтобы не плодить дебликаты, там пока 20 
> строк но я уже пару раз задублировал параметры :confused:
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MegoHappyThreeFriends/JustTrade/issues/15>.
>

-- 
  Dmitry Ermakov

**Comment by greshniksv** [comment]
Вот я и не знаю как быть, я думал запихнуть Lang файл в ресурсы, но тогда они будут доступны только для чтения. И функционал с редактирование будет не нужен.

**Comment by dimerr** [comment]
On 06/12/2015 10:44 PM, Сергей Раткин wrote:
>
> Вот я и не знаю как быть, я думал запихнуть Lang файл в ресурсы, но 
> тогда они будут доступны только для чтения. И функционал с 
> редактирование будет не нужен.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MegoHappyThreeFriends/JustTrade/issues/15#issuecomment-111597439>.
>

ну а как их создавать, просто в текстовом редакторе, что ли?

-- 
  Dmitry Ermakov

**Comment by greshniksv** [comment]
ну хз, я пока об этом не думал, но инструмент для этого точно нужен. Может просто гуиншую прогу сделать ?

**Comment by dimerr** [comment]
On 06/12/2015 10:50 PM, Сергей Раткин wrote:
>
> ну хз, я пока об этом не думал, но инструмент для этого точно нужен. 
> Может просто гуиншую прогу сделать ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MegoHappyThreeFriends/JustTrade/issues/15#issuecomment-111598421>.
>
лучше в составе основного проекта может, тошо гуишную прогу может и 
негде запустить будет кому-то

-- 
  Dmitry Ermakov

**Comment by greshniksv** [comment]
Согласен. Тогда вынесу Lang файл из ресурсов и добавлю раздел редактирование ресурсов в админку.
